# Generated by Django 4.0.5 on 2022-06-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_details',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
